
volumes:
  sqlserver_data:
    
networks:
  blog_network:
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    # If you really want to use MS SQL Server, uncomment the following line
    #image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "123456@qwerty"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
    ports:
        - "1433:1433"
    volumes:
        - sqlserver_data:/var/opt/mssql
    networks:
        - blog_network


#https://github.com/docker/awesome-compose/